package com.example.lynx.flex.a.utilities;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Base64.Encoder;

import com.example.lynx.core.a.exception.JaxBasicRuntimeException;
import com.example.lynx.core.b.exceptions.JaxForbiddenConstructorException;
import com.example.lynx.core.c.utility.types.JaxString;

public final class JaxOpaqueTokenValueUtility
{
  private JaxOpaqueTokenValueUtility() { throw JaxForbiddenConstructorException.create(JaxOpaqueTokenValueUtility.class); }

  private static final SecureRandom SECURE_RANDOM = new SecureRandom();
  private static final Encoder ENCODER = Base64.getUrlEncoder().withoutPadding();

  /**
   * <h4>Function</h4>
   * <ul>
   * <li>This method will generate 32 bytes and then encode those bytes using a Base 64 URL Without Padding Encoder.</li>
   * </ul>
   * 
   * <h4>Returns</h4>
   * <ul>
   * <li>a Base 64 URL Without Padding Encoded {@link String} derived from 32 randomly generated bytes</li>
   * </ul>
   */
  public static String generate() {
    final byte[] bytes = new byte[32];
    SECURE_RANDOM.nextBytes(bytes);
    return ENCODER.encodeToString(bytes);
  }

  /**
   * <h4>Function</h4>
   * <ul>
   * <li>This method will hash an instance of {@link String} using the {@code SHA-256} algorithm.</li>
   * </ul>
   * 
   * <h4>Parameters</h4>
   * <ul>
   * <li>{@code actual} - an instance of {@link String} / the actual value</li>
   * </ul>
   * 
   * <h4>Returns</h4>
   * <ul>
   * <li>a new instance of {@link String}  the hashed value</li>
   * </ul>
   * 
   * <h4>Throws</h4>
   * <ul>
   * <li>{@link JaxBasicRuntimeException} if the {@code SHA-256} algorithm is not supported</li>
   * </ul>
   * 
   * <h4>Standard</h4>
   */
  public static String hash(String actual) {
    JaxString.require(actual);
    try {
      final MessageDigest digest = MessageDigest.getInstance("SHA-256");
      final byte[] hash = digest.digest(actual.getBytes(StandardCharsets.UTF_8));
      return ENCODER.encodeToString(hash);
    }
    catch (NoSuchAlgorithmException exception) {
      throw new JaxBasicRuntimeException(String.format("Error Hashing Opaque Token Value [%s]", JaxString.REDACTED), exception);
    }
  }
}
